### ISSUE TITLE
ImportError: cannot import name 'parse_translation_arguments

### ISSUE THREAD

**Issue by Tortoise17** [sign-language-processing/signwriting-translation#1]
There is error, I am not sure if this comes from sockeye or from the parser of this repo.

input command was 
$`signwriting_to_text --spoken-language="en" --signed-language="ase" --input="M525x535S2e748483x510S10011501x466S2e704510x500S10019476x475"`

and the error is 
```

from sockeye.translate import parse_translation_arguments, load_translator_from_args
ImportError: cannot import name 'parse_translation_arguments' from 'sockeye.translate'
```
I tried to downgrade the sockeye and other versions. But problem exists. If you can hint what could be reason.

**Comment by AmitMY** [comment]
In the package toml file, you can find the relevant sockeye version:
>    "sockeye @ git+https://github.com/sign-language-processing/sockeye",

**Comment by Tortoise17** [comment]
It is same. But error is again the same. Cloning this version and pip install -e . provides `3.1.38` version of `sockeye`
